### ISSUE TITLE
successfully registered but can't enter app

### ISSUE THREAD

**Issue by elionchin** [jsappme/TreeTheWorld#1]
it appears i was able to register with name 'elion' and email address 'elionchin@gmail.com'. after temporary 'registering' system message it takes me back to the splash screen. from there i then proceed to sign in (already a lover) and after temporary 'logging in' system message it again takes me back to the splash screen with a '< Back' navigation at top left. of course i don't know if that is intended function at the moment.

**Comment by jsappme** [comment]
I think you re still using the first version. The new version is 0.0.2. Please verify.

**Comment by elionchin** [comment]
I just saw that for some reason the new version does not just automatically replace the old one in the testflight center and i have to go into the email to accept the invitation. Now installing 0.02
