### ISSUE TITLE
iconography & bottom tabs

### ISSUE THREAD

**Issue by elionchin** [jsappme/TreeTheWorld#3]
I feel at the moment the different tab icons are not yet intuitive enough. I think removing the tree itself from the icons will provide more flexibility. suggestions:

1. map view: maybe use classic map icon
2. list view based on my position (distance would be cool to see in each post): maybe use more of a list icon (three vertical bars)

{1 and 2 are exploration views so they could even have a joint background that is slightly different from the others}

3. submit new tree: use some sort of "+", here tree outline might be good (add tree). maybe make this bigger than others?
4. trees i follow: maybe just a few overlapping stars. i would then add the star also to the 'follow' button so the association is consistent
5. trees/photos i uploaded: i almost feel you could merge those into 4 (and consider having a filter within that view to toggle only your trees vs yours plus the ones you folow) and use that tab for the DONATION section altogether (that icon would actually work perfectly).

**Comment by jsappme** [comment]
this is not an issue just a personal taste. please send your icons to the ttw whatsapp chat so we can decide which ones are the best. concerning merging the two views, i tried but it's not working.
