### ISSUE TITLE
like vs following

### ISSUE THREAD

**Issue by elionchin** [jsappme/TreeTheWorld#4]
i was confused by liking vs following. because when only one pic exists (the initial one) then the difference is not obvious. i somehow thought when i would like a tree i would see it in my 'starred' view, but realized that liking is specific to the photo. don't have the solution though... . of course after using it for a while it starts resolving itself, but ideally its clear right away. i think also would be good if somehow we could convey what 'following' a tree does (notify of new stories or pictures attached, etc)

**Comment by jsappme** [comment]
again this is not a bug nor an issue. if you have a simple and clear idea how to add value to the app, please feel free to add it and reopen it
